### ISSUE TITLE
Additional client-side fetching with SSR

### ISSUE THREAD

**Issue by steve-jiang** [algolia/shopify-hydrogen-algolia#8]
Hi team,

Thanks for the demo implementation.

My question is when testing with your demo store. Move from collection to collection, despite the results are already SSRed, you can see there is still an additional client-site fetching in the network tab. 

Is it intended and if so what is the reason? If not, how can we get rid of this additional request? Since all search queries count towards the overall usage, I'd think it makes sense to not over-fetching if possible.

Thank you!

**Comment by steve-jiang** [comment]
Another issue with the demo store is that when you navigate to a collection page, and then hit the browser back button, it triggers another client-side fetching on the prev route/collection. 

So let's say you go from `Mens -> Home` (instead of clicking the home link, hit the browser's back button), you will see a client-side fetching in the network tab against the `Mens` collection which is just a wasted fetch. That fetch will never get any clicks but it sure counts towards insight analytics as a search.

**Comment by qinglinye** [comment]
Hello,
In fact, for our React InstantSearch Hooks library, only the initial request is SSR (when we inject serverState), after it will be client-side rendering to increase the performance since our SSR is only designed for hydration for SEO. The collection pages are all handled by a single instantsearch instance in the template, without refreshing the page, it will be CSR after first rendering so it is not an additional request. Please check with our support team for further questions regarding UI libraries.
Thanks

**Comment by steve-jiang** [comment]
Hi @qinglinye 

Thanks for looking into it. 

I am not sure what you said applies to Hydrogen/Remix. Since your data fetching is inside Remix's loader, on every route change and action, the loader will fetch Algolia again. If your implementation is meant to fetch on the client side after the initial page load, you'd still have a server-side fetch in the loader that is essentially wasted.

You can verify it by adding a console.log in your loader and see if Algolia fetches at the server side upon route changes.

Do you want me to raise this issue in the instantsearch repo instead of here so more people can have a look?

Thanks again!

**Comment by qinglinye** [comment]
Hello,
The serverState normally is not calculated in this case since it depends on uiState for after first rendering. I took sometime to check the API logs and for the demo template we got only single request not duplicated ones for collection pages. You can also create separated router for each collection if you want SSR when navigation.
For detailed UI related questions, please check with our support team. We are currently in best effort mode for answering questions in this github so your question may remain unanswered for a period of time.

Thanks

**Comment by sefai** [comment]
Hello @qinglinye, I am having the same issue with my remix app. While I was searching for an answer I came across this repo and saw this issue: serverState is definitely calculated as you can see from the screenshot. 

<img width="1511" alt="Screenshot 2024-06-30 at 14 28 22" src="https://github.com/algolia/shopify-hydrogen-algolia/assets/18752451/1da5cf9e-dd68-487b-8c86-9ddd2c5b6c26">

**Comment by sefai** [comment]
It is not just client-side routing, a full refresh of collections also performs a client-side query after serving the SSR'ed page.

<img width="1507" alt="Screenshot 2024-06-30 at 15 04 08" src="https://github.com/algolia/shopify-hydrogen-algolia/assets/18752451/6bd56af3-05a4-4b99-8a8c-a16b92df20e6">
